### ISSUE TITLE
Bad decoding of revision & serial (?)

### ISSUE THREAD

**Issue by guyit** [ornl-epics/etherip#4]
Dear developer,
In your project, as part of the connect procedure we get the device info, in particular the revision and serial of the PLC.
I noted that these two values, while running etherip are different then it displayed in RSLinx.
As for the revision - you considered the revision's 2 bytes as a short, while RSLinx are using each byte as a number the first is kind of major revision number and the second is minor revision number, so eventually they display it as, for instance, 2.4 and I wonder from your experience what data type the revision number is?
In regards to the serial - while sniffing the network (wireshark) I see that the revision number is 4 bytes long while you consider it as short.    

Please note that I'm using MicroLogic PLC (the connect phase is no different than the PLCs you do support) and all I care is connecting to the PLC not reading tags from it.
I saw that every thing works fine besides these 2 exceptions. 

I'm new with CIP and I would appreciate your help.
Many thanks!

**Comment by kasemir** [comment]
Hi:

Looks like you're right.
The "Identity" object as described in my copy of the EtherNet/IP specification indeed has an UDINT for attribute 6 = serial number, not an UINT.

So in EtherNetIP.java, line 105 should be something like
```
final int serial = getLongAttribute(6);
```
instead of 
```
final short serial = getShortAttribute(6);
```
where `getLongAttribute` needs to be implemented and the `DeviceInfo` needs to be updated to take the larger serial number type.
`getLongAttribute` will also need a `GetLongAttributeProtocol` which is just like the existing `GetShortAttributeProtocol` but replacing `buf.getShort` with, I think, `buf.getInt`.

You're also right that the revision is maybe better interpreted as a major.minor value, which could be handled by for example printing it that way in `DeviceInfo.toString()`.

Feel free to implement that and submit a pull request, which I'd be glad to merge.
Thanks for improving the source code!

**Comment by kasemir** [comment]
Closing since there's now also the getIdentity method that fetches all attributes:
```
./etherip -i  xx.xx.xx.xx IDENTITY
Identity [vendorId=1, deviceType=12, productCode=58, revision=[4, 3], productName=1756-ENBT/A, serialNumber=0x00412C49, status=0x0060]
```
